name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Sadece main dalına kod gönderildiğinde çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sunucuya Bağlan ve Güncelle
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/realtime-finance
            # Sunucudaki nano değişikliklerini veya çakışmaları zorla ezip GitHub'daki en güncel haliyle eşitler
            git fetch --all
            git reset --hard origin/main
            git clean -fd
            # Sistemi yeni kodlarla yeniden başlatır
            docker-compose up -d